apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: montest1-hpa
  labels:
    app: montest1
    version: 0.0.1
    backstage.io/kubernetes-id: montest1
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: montest1
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75